#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git merge" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message to
# stderr if it wants to stop the merge commit.
# Author: Nanda Kishor J

# currently this is customized one for checkout
test -x "$(git rev-parse --git-path hooks)/pre-commit" &&
        exec "$(git rev-parse --git-path hooks)/pre-commit" true 

