pipeline:
  clone:
    image: plugins/git
    when:
      event:
        exclude: [deployment]
        include: [push]
  build:
    image: docker:17.12.0-ce-dind
    environment:
     - DOCKER_HOST=unix:///drone/docker.sock
     - GIT_COMMIT_HASH=${DRONE_COMMIT_SHA}
    secrets: [docker_username, docker_password]
    commands:
     - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
     - docker build --quiet=false -t razorpay/checkout:$${GIT_COMMIT_HASH} . --build-arg GIT_COMMIT_HASH=$${GIT_COMMIT_HASH}
     - docker push razorpay/checkout:$${GIT_COMMIT_HASH}
    when:
      status: [success]
      event:
        exclude: [deployment, pull_request, tag]
        include: [push]
  deploy-stage:
    image: razorpay/drone-kubernetes
    pull: true
    secrets:
      - docker_username
      - docker_password
      - server_url_stage
      - server_cert_stage
      - client_cert_stage
      - client_key_stage
    user: drone
    cluster: stage
    auth_mode: client-cert
    deployment: checkout
    repo: razorpay/checkout
    namespace: pos
    tag:
      - ${DRONE_COMMIT_SHA}
    when:
      environment: stage
      event:
        exclude: [push]
        include: [deployment]
  deploy-prod:
    image: razorpay/drone-kubernetes
    pull: true
    secrets:
      - docker_username
      - docker_password
      - server_url_prod
      - server_cert_prod
      - client_cert_prod
      - client_key_prod
    user: drone
    cluster: prod
    auth_mode: client-cert
    deployment: checkout
    repo: razorpay/checkout
    namespace: pos
    tag:
      - ${DRONE_COMMIT_SHA}
    when:
      environment: prod
      event:
        exclude: [push]
        include: [deployment]
  build-notify:
    image: plugins/slack
    secrets: [slack_webhook]
    channel: tech_distelli
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      {{#success build.status}}
        Build succeeded.
      {{else}}
        Build failed.
      {{/success}}
        Build No:{{build.number}}
        Branch: {{build.branch}}
        Commit: {{build.commit}}
        Author: {{build.author}}
        Started at: {{build.started}}
        Time taken: {{since build.started}}
        Link: {{build.link}}
    when:
      event:
        exclude: [deployment]
        include: [push]
services:
  docker:
    image: docker:17.12.0-ce-dind
    privileged: true
    command: [ '-H', 'unix:///drone/docker.sock' ]
