const UPI_UX = {
  APP_FLOW_ABSENT_FALLBACK_OTHERS: 'APP_FLOW_ABSENT_FALLBACK_OTHERS',
  OTHERS_SELECTED: 'OTHERS_SELECTED',
  APP_SELECTED: 'APP_SELECTED',
  USER_CANCEL_ON_IOS_MWEB: 'USER_CANCEL_ON_IOS_MWEB',
  TAB_DESTROY_ON_IOS_MWEB: 'TAB_DESTROY_ON_IOS_MWEB',
  INTENT_FAILED: 'INTENT_FAILED',
};
const QR_ON_L1 = {
  REFRESH_QR_ON_L1: 'REFRESH_QR_ON_L1',
  QR_ON_L1: 'QR_ON_L1',
  QR_ON_L1_EXPIRED: 'QR_ON_L1_EXPIRED',
};

export const EVENTS = {
  ...UPI_UX,
  ...QR_ON_L1,
};

export const TRACES = {
  FEE_MODAL_TRIGGERED: 'FEE_MODAL_TRIGGERED',
  IOS_MWEB_TAB_CREATED: 'IOS_MWEB_TAB_CREATED',
  IOS_MWEB_TAB_FORCE_DESTROY_CALLED: 'IOS_MWEB_TAB_FORCE_DESTROY_CALLED',
  IOS_MWEB_TAB_DESTROY_CALLED: 'IOS_MWEB_TAB_DESTROY_CALLED',
  IOS_MWEB_TAB_URL_SET: 'IOS_MWEB_TAB_URL_SET',
  IOS_MWEB_TAB_NO_PARENT_EVENTS: 'IOS_MWEB_TAB_NO_PARENT_EVENTS',
  IOS_MWEB_PARENT_FOCUS_TIMEOUT: 'IOS_MWEB_PARENT_FOCUS_TIMEOUT',
  IOS_MWEB_CONSENT_CANCELLED: 'IOS_MWEB_CONSENT_CANCELLED',
  IOS_MWEB_CONSENT_OPENED: 'IOS_MWEB_CONSENT_OPENED',
  IOS_MWEB_FIRST_TIMEOUT: 'IOS_MWEB_FIRST_TIMEOUT',
  INTENT_PROMISE_RESOLVED: 'INTENT_PROMISE_RESOLVED',
  FEE_MODAL_WAITING_FOR_USER: 'FEE_MODAL_WAITING_FOR_USER',
  FEE_MODAL_USER_CONSENT_TAKEN: 'FEE_MODAL_USER_CONSENT_TAKEN',
  OTHERS_SELECTED: 'OTHERS_SELECTED',
  APP_SELECTED: 'APP_SELECTED',
  ACTION_TRIGGERED: 'ACTION_TRIGGERED',
  APP_FLOW_ABSENT_FALLBACK_OTHERS: 'APP_FLOW_ABSENT_FALLBACK_OTHERS',
};
