const UPI_UX = {
  APP_FLOW_ABSENT_FALLBACK_OTHERS: 'APP_FLOW_ABSENT_FALLBACK_OTHERS',
  OTHERS_SELECTED: 'OTHERS_SELECTED',
  APP_SELECTED: 'APP_SELECTED',
  USER_CANCEL_ON_IOS_MWEB: 'USER_CANCEL_ON_IOS_MWEB',
  TAB_DESTROY_ON_IOS_MWEB: 'TAB_DESTROY_ON_IOS_MWEB',
  INTENT_FAILED: 'INTENT_FAILED',
};

const QR_EVENTS = {
  QR_SECTION_RENDERED: 'QR_SECTION',
  QR_CTA_CLICK: 'QR_CTA_CLICK',
  QR_RENDERED: 'QR_LOADED',
  QR_EXPIRED: 'QR_EXPIRED',
};

export const EVENTS = {
  ...UPI_UX,
  ...QR_EVENTS,
};

export const TRACES = {
  FEE_MODAL_TRIGGERED: 'FEE_MODAL_TRIGGERED',
  IOS_MWEB_TAB_CREATED: 'IOS_MWEB_TAB_CREATED',
  IOS_MWEB_TAB_URL_SET: 'IOS_MWEB_TAB_URL_SET',
  IOS_MWEB_TAB_NO_PARENT_EVENTS: 'IOS_MWEB_TAB_NO_PARENT_EVENTS',
  IOS_MWEB_PARENT_FOCUS_TIMEOUT: 'IOS_MWEB_PARENT_FOCUS_TIMEOUT',
  IOS_MWEB_CONSENT_CANCELLED: 'IOS_MWEB_CONSENT_CANCELLED',
  IOS_MWEB_CONSENT_OPENED: 'IOS_MWEB_CONSENT_OPENED',
  IOS_MWEB_FIRST_TIMEOUT: 'IOS_MWEB_FIRST_TIMEOUT',
  INTENT_PROMISE_RESOLVED: 'INTENT_PROMISE_RESOLVED',
  FEE_MODAL_WAITING_FOR_USER: 'FEE_MODAL_WAITING_FOR_USER',
  FEE_MODAL_USER_CONSENT_TAKEN: 'FEE_MODAL_USER_CONSENT_TAKEN',
  ACTION_TRIGGERED: 'ACTION_TRIGGERED',
};
