module.exports = {
  ajaxResponse: {
    type: 'first',
    request: {
      url:
        'https://api.razorpay.com/v1/gateway/mocksharp/payment?key_id=rzp_test_1DP5mmOlF5G5ag&action=authorize&amount=200&method=card&payment_id=GZ7c6a2d9mfWAG&callback_url=https%3A%2F%2Fapi.razorpay.com%2Fv1%2Fpayments%2Fpay_GZ7c6a2d9mfWAG%2Fcallback%2F003a66d043ae11dc4cb2b29a3f089c465628b794%2Frzp_test_1DP5mmOlF5G5ag&recurring=0&card_number=eyJpdiI6ImJNT0cyQWdHbzliRGtMWVNBNHk3SVE9PSIsInZhbHVlIjoiZ0Vodkx3UmlVcUczS2NlK09OZFwvQmgzR1NXSWRLXC9LUVJLQUdsYzg1OTRjPSIsIm1hYyI6Ijk0ZjM2ODM4MzQzNGYzNTVjOWVjNWFiMWRjYjJiZWJiOWQ2MzhkMzQzOGFlNDc4MWU5NmZlOTEwYzNlNGE0YjEifQ%3D%3D&encrypt=1',
      method: 'get',
      content: [],
    },
    version: 1,
    payment_id: 'pay_GZ7c6a2d9mfWAG',
    gateway:
      'eyJpdiI6IkJhNEQrb0cwcWpoZEIwYmU2UVNDNkE9PSIsInZhbHVlIjoiRnA0SXpXV3NUNXdmSDlVQ3p1MWhyZDlNT05oRTZkQzN0WjJhd2VNeTlydz0iLCJtYWMiOiI5Y2Y3NzVlN2M2OTc2NTIwN2JiM2ZkMGYzMGZhZmFhY2I0YTJiNTRiNjA2NTJlNTMxODM2MDNjZGY5NmIzZTMxIn0=',
    amount: '₹ 2',
    image: 'https://cdn.razorpay.com/logos/GS8xtzE45HDhNT_medium.png',
    magic: false,
    org_logo: '',
    org_name: 'Razorpay Software Private Ltd',
    checkout_logo:
      'https://dashboard-activation.s3.amazonaws.com/org_100000razorpay/checkout_logo/phpnHMpJe',
    custom_branding: false,
  },
  validVPAResponse: (vpa, override = {}) => ({
    customer_name: null,
    success: true,
    vpa,
    ...override
  }),
  invalidVPAResponse: () => ({
    error: {
      code: 'BAD_REQUEST_ERROR',
      description: 'Invalid VPA. Please enter a valid Virtual Payment Address',
      field: 'vpa',
      metadata: {},
      reason: 'NA',
      source: 'NA',
      step: 'NA',
    },
  }),
  calculateFees: (override = {}) => ({
    input: {
      contact: '+919999999999',
      email: 'qa.testing@razorpay.com',
      method: 'card',
      card: {
        number: '4111111111111111',
        cvv: '123',
        name: 'arshpreet',
        expiry_month: '11',
        expiry_year: '22',
      },
      save: '1',
      amount: 6120,
      currency: 'INR',
      description: 'JEE Main & Advanced',
      _: {
        shield: {
          fhash: '1be193c1839c79f3e9d74400ee5c8a8d3d4e2ee3',
          tz: '330',
        },
        device_id:
          '1.dae48d101d6487d1d505d0a8028fa55ad6deb72c.1608202514893.10168615',
        build: '0',
        checkout_id: 'Gc8cBVREqsv97G',
        library: 'checkoutjs',
        platform: 'browser',
        referer: 'https://checkout.local/',
      },
      fee: 120,
    },
    display: {
      originalAmount: 60,
      original_amount: 60,
      fees: 1.2,
      razorpay_fee: 1.2,
      tax: 0,
      amount: 61.2,
      org_logo: '',
      org_name: 'Razorpay Software Private Ltd',
      checkout_logo:
        'https://dashboard-activation.s3.amazonaws.com/org_100000razorpay/checkout_logo/phpnHMpJe',
      custom_branding: false,
    },
    ...override,
  }),
  preferences: (override = {}) => ({
    options: { theme: { color: null }, image: null, remember_customer: false },
    fee_bearer: false,
    version: 1,
    language_code: 'en',
    merchant_id: '10000000000000',
    mode: 'test',
    magic: true,
    methods: {
      entity: 'methods',
      card: true,
      debit_card: true,
      credit_card: true,
      prepaid_card: true,
      card_networks: {
        AMEX: 0,
        DICL: 1,
        MC: 0,
        MAES: 1,
        VISA: 1,
        JCB: 1,
        RUPAY: 1,
        BAJAJ: 0,
      },
      card_subtype: { consumer: 1, business: 0 },
      amex: false,
      netbanking: {
        AUBL: 'AU Small Finance Bank',
        AIRP: 'Airtel Payments Bank',
        ALLA: 'Allahabad Bank',
        ANDB: 'Andhra Bank',
        ANDB_C: 'Andhra Bank - Corporate Banking',
        UTIB: 'Axis Bank',
        BDBL: 'Bandhan Bank',
        BBKM: 'Bank of Bahrein and Kuwait',
        BARB_R: 'Bank of Baroda - Retail Banking',
        BKID: 'Bank of India',
        MAHB: 'Bank of Maharashtra',
        BACB: 'Bassein Catholic Co-operative Bank',
        CITI: 'CITI Bank',
        CNRB: 'Canara Bank',
        CSBK: 'Catholic Syrian Bank',
        CBIN: 'Central Bank of India',
        CIUB: 'City Union Bank',
        COSB: 'Cosmos Co-operative Bank',
        DCBL: 'DCB Bank',
        DEUT: 'Deutsche Bank',
        DBSS: 'Development Bank of Singapore',
        DLXB: 'Dhanlaxmi Bank',
        DLXB_C: 'Dhanlaxmi Bank - Corporate Banking',
        ESAF: 'ESAF Small Finance Bank',
        ESFB: 'Equitas Small Finance Bank',
        FDRL: 'Federal Bank',
        FSFB: 'Fincare Small Finance Bank',
        HDFC: 'HDFC Bank',
        ICIC: 'ICICI Bank',
        IBKL: 'IDBI',
        IBKL_C: 'IDBI - Corporate Banking',
        IDFB: 'IDFC FIRST Bank',
        IDIB: 'Indian Bank',
        IOBA: 'Indian Overseas Bank',
        INDB: 'Indusind Bank',
        JAKA: 'Jammu and Kashmir Bank',
        JSFB: 'Jana Small Finance Bank',
        JSBP: 'Janata Sahakari Bank (Pune)',
        KCCB: 'Kalupur Commercial Co-operative Bank',
        KJSB: 'Kalyan Janata Sahakari Bank',
        KARB: 'Karnataka Bank',
        KVBL: 'Karur Vysya Bank',
        KKBK: 'Kotak Mahindra Bank',
        LAVB_C: 'Lakshmi Vilas Bank - Corporate Banking',
        LAVB_R: 'Lakshmi Vilas Bank - Retail Banking',
        MSNU: 'Mehsana Urban Co-operative Bank',
        NKGS: 'NKGSB Co-operative Bank',
        NESF: 'North East Small Finance Bank',
        ORBC: 'PNB (Erstwhile-Oriental Bank of Commerce)',
        UTBI: 'PNB (Erstwhile-United Bank of India)',
        PSIB: 'Punjab & Sind Bank',
        PUNB_R: 'Punjab National Bank - Retail Banking',
        RATN: 'RBL Bank',
        RATN_C: 'RBL Bank - Corporate Banking',
        ABNA: 'Royal Bank of Scotland N.V.',
        SRCB: 'Saraswat Co-operative Bank',
        SVCB_C: 'Shamrao Vithal Bank - Corporate Banking',
        SVCB: 'Shamrao Vithal Co-operative Bank',
        SIBL: 'South Indian Bank',
        SCBL: 'Standard Chartered Bank',
        SBBJ: 'State Bank of Bikaner and Jaipur',
        SBHY: 'State Bank of Hyderabad',
        SBIN: 'State Bank of India',
        SBMY: 'State Bank of Mysore',
        STBP: 'State Bank of Patiala',
        SBTR: 'State Bank of Travancore',
        SURY: 'Suryoday Small Finance Bank',
        SYNB: 'Syndicate Bank',
        TMBL: 'Tamilnadu Mercantile Bank',
        TNSC: 'Tamilnadu State Apex Co-operative Bank',
        TBSB: 'Thane Bharat Sahakari Bank',
        TJSB: 'Thane Janata Sahakari Bank',
        UCBA: 'UCO Bank',
        UBIN: 'Union Bank of India',
        CORP: 'Union Bank of India (Erstwhile Corporation Bank)',
        VARA: 'Varachha Co-operative Bank',
        YESB: 'Yes Bank',
        YESB_C: 'Yes Bank - Corporate Banking',
        ZCBL: 'Zoroastrian Co-operative Bank',
      },
      wallet: {
        mobikwik: true,
        payzapp: true,
        olamoney: true,
        airtelmoney: true,
        jiomoney: true,
        sbibuddy: true,
        openwallet: true,
        phonepe: true,
      },
      emi: true,
      upi: true,
      cardless_emi: { earlysalary: true },
      paylater: [],
      google_pay_cards: false,
      app: { cred: 0 },
      nach: false,
      bank_transfer: true,
      emi_subvention: 'merchant',
      emi_plans: {
        HDFC: { min_amount: 300000, plans: { '6': 1, '9': 1, '12': 1.23 } },
        HSBC: { min_amount: 350000, plans: { '3': 1 } },
        AMEX: { min_amount: 1349900, plans: { '9': 1 } },
        ICIC: { min_amount: 300000, plans: { '12': 1 } },
        BAJAJ: { min_amount: 300000, plans: { '6': 1, '9': 1 } },
        NULL: { min_amount: 300000, plans: { '3': 0.01, '6': 1, '9': 0.12 } },
        RATN: { min_amount: 300000, plans: { '3': 1, '6': 12.34 } },
        UTIB: { min_amount: 100000, plans: { '3': 10 } },
        KKBK: { min_amount: 300000, plans: { '3': 12, '9': 14 } },
      },
      emi_options: {
        HDFC: [
          {
            duration: 12,
            interest: 1.23,
            subvention: 'customer',
            min_amount: 143,
            merchant_payback: '0.66',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 9,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.00',
          },
        ],
        HSBC: [
          {
            duration: 3,
            interest: 1,
            subvention: 'customer',
            min_amount: 350000,
            merchant_payback: '0.17',
          },
        ],
        AMEX: [
          {
            duration: 9,
            interest: 1,
            subvention: 'customer',
            min_amount: 1349900,
            merchant_payback: '0.42',
          },
        ],
        ICIC: [
          {
            duration: 12,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.54',
          },
        ],
        BAJAJ: [
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.00',
          },
          {
            duration: 9,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.42',
          },
        ],
        NULL: [
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.05',
          },
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 1,
            merchant_payback: '0.05',
          },
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 1,
            merchant_payback: '0.05',
          },
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 1,
            merchant_payback: '0.05',
          },
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 1,
            merchant_payback: '0.05',
          },
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 1,
            merchant_payback: '0.05',
          },
          {
            duration: 9,
            interest: 0.12,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.05',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '0.00',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
          {
            duration: 6,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.29',
          },
        ],
        RATN: [
          {
            duration: 3,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.17',
          },
          {
            duration: 6,
            interest: 12.34,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '3.50',
          },
        ],
        UTIB: [
          {
            duration: 3,
            interest: 1,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.17',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '-0.17',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 100,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 100,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 1.9,
            subvention: 'customer',
            min_amount: 100,
            merchant_payback: '0.32',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 100,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 100,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 1000,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 991,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 991,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 991,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 0.01,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '0.00',
          },
          {
            duration: 3,
            interest: 10,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '1.64',
          },
          {
            duration: 3,
            interest: 10,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '1.64',
          },
          {
            duration: 3,
            interest: 10,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '1.64',
          },
          {
            duration: 3,
            interest: 10,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '1.64',
          },
          {
            duration: 3,
            interest: 10,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '1.64',
          },
          {
            duration: 3,
            interest: 10,
            subvention: 'customer',
            min_amount: 100000,
            merchant_payback: '1.64',
          },
        ],
        KKBK: [
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 3,
            interest: 12,
            subvention: 'customer',
            min_amount: 10000,
            merchant_payback: '1.97',
          },
          {
            duration: 9,
            interest: 14,
            subvention: 'customer',
            min_amount: 300000,
            merchant_payback: '0.00',
          },
        ],
      },
      recurring: {
        card: { credit: ['MasterCard', 'Visa'] },
        emandate: {
          ANDB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Andhra Bank',
          },
          UTIB: { auth_types: ['netbanking', 'debitcard'], name: 'Axis Bank' },
          BDBL: { auth_types: ['netbanking'], name: 'Bandhan Bank' },
          BARB_R: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Bank of Baroda - Retail Banking',
          },
          MAHB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Bank of Maharashtra',
          },
          CITI: { auth_types: ['netbanking', 'debitcard'], name: 'CITI Bank' },
          CNRB: { auth_types: ['netbanking'], name: 'Canara Bank' },
          CBIN: { auth_types: ['netbanking'], name: 'Central Bank of India' },
          CIUB: { auth_types: ['netbanking'], name: 'City Union Bank' },
          COSB: {
            auth_types: ['netbanking'],
            name: 'Cosmos Co-operative Bank',
          },
          DEUT: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Deutsche Bank',
          },
          DBSS: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Development Bank of Singapore',
          },
          DLXB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Dhanlaxmi Bank',
          },
          ESFB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Equitas Small Finance Bank',
          },
          FDRL: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Federal Bank',
          },
          HDFC: { auth_types: ['netbanking', 'debitcard'], name: 'HDFC Bank' },
          HSBC: {
            auth_types: ['netbanking'],
            name: 'Hongkong & Shanghai Banking Corporation',
          },
          ICIC: { auth_types: ['netbanking', 'debitcard'], name: 'ICICI Bank' },
          IBKL: { auth_types: ['netbanking'], name: 'IDBI' },
          IDFB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'IDFC FIRST Bank',
          },
          IOBA: { auth_types: ['netbanking'], name: 'Indian Overseas Bank' },
          INDB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Indusind Bank',
          },
          JSFB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Jana Small Finance Bank',
          },
          KARB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Karnataka Bank',
          },
          KVBL: { auth_types: ['netbanking'], name: 'Karur Vysya Bank' },
          KKBK: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Kotak Mahindra Bank',
          },
          PYTM: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Paytm Payments Bank',
          },
          PSIB: { auth_types: ['netbanking'], name: 'Punjab & Sind Bank' },
          PUNB_R: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Punjab National Bank - Retail Banking',
          },
          RATN: { auth_types: ['netbanking', 'debitcard'], name: 'RBL Bank' },
          SIBL: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'South Indian Bank',
          },
          SCBL: { auth_types: ['netbanking'], name: 'Standard Chartered Bank' },
          SBIN: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'State Bank of India',
          },
          SYNB: { auth_types: ['netbanking'], name: 'Syndicate Bank' },
          TMBL: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Tamilnadu Mercantile Bank',
          },
          USFB: {
            auth_types: ['netbanking', 'debitcard'],
            name: 'Ujjivan Small Finance Bank',
          },
          UBIN: { auth_types: ['netbanking'], name: 'Union Bank of India' },
          YESB: { auth_types: ['netbanking', 'debitcard'], name: 'Yes Bank' },
          AUBL: { auth_types: ['debitcard'], name: 'AU Small Finance Bank' },
          DCBL: { auth_types: ['debitcard'], name: 'DCB Bank' },
        },
        upi: true,
        nach: false,
      },
      upi_intent: true,
      upi_type: { collect: 1, intent: 1 },
    },
    global: true,
    downtime: {
      upi: [
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1612774781 },
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1612773737 },
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1608724372 },
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1608723767 },
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1608721499 },
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1608721499 },
        { issuer: ['UNKNOWN'], severity: 'high', begin: 1605870988 },
      ],
      netbanking: [{ issuer: ['SBIN'], severity: 'high', begin: 1610451216 }],
    },
    payment_downtime: {
      entity: 'collection',
      count: 7,
      items: [
        {
          id: 'down_GG7PVJCCxh3qLr',
          entity: 'payment.downtime',
          method: 'card',
          begin: 1608647316,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { network: 'VISA' },
          created_at: 1608647326,
          updated_at: 1608647326,
        },
        {
          id: 'down_GGSTgMwvjcMy0L',
          entity: 'payment.downtime',
          method: 'upi',
          begin: 1608721499,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { vpa_handle: 'oksbi' },
          created_at: 1608721517,
          updated_at: 1608721517,
        },
        {
          id: 'down_GGSViBpQ3628yA',
          entity: 'payment.downtime',
          method: 'upi',
          begin: 1608721499,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { vpa_handle: 'okhdfcbank' },
          created_at: 1608721632,
          updated_at: 1608721632,
        },
        {
          id: 'down_GGT7jMZDQtfrwN',
          entity: 'payment.downtime',
          method: 'upi',
          begin: 1608723767,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { vpa_handle: 'okaxis' },
          created_at: 1608723792,
          updated_at: 1608723792,
        },
        {
          id: 'down_GGTIDRJWRoGraq',
          entity: 'payment.downtime',
          method: 'upi',
          begin: 1608724372,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { vpa_handle: 'okicici' },
          created_at: 1608724387,
          updated_at: 1608724387,
        },
        {
          id: 'down_GZ1FIN052YvST6',
          entity: 'payment.downtime',
          method: 'upi',
          begin: 1612773737,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { vpa_handle: 'ALL' },
          created_at: 1612774078,
          updated_at: 1612774078,
        },
        {
          id: 'down_GZ1Rormx7gMyiE',
          entity: 'payment.downtime',
          method: 'upi',
          begin: 1612774781,
          end: null,
          status: 'started',
          scheduled: false,
          severity: 'high',
          instrument: { vpa_handle: 'oksbi' },
          created_at: 1612774790,
          updated_at: 1612774790,
        },
      ],
    },
    features: { dcc: true },
    org: {
      id: '100000razorpay',
      business_name: 'Razorpay',
      display_name: 'Razorpay Software Private Ltd',
      email: 'admin@razorpay.com',
      type: null,
      auth_type: 'password',
      email_domains: ['razorpay.com'],
      allow_sign_up: true,
      login_logo_url: null,
      main_logo_url: null,
      invoice_logo_url: null,
      custom_code: 'rzp',
      from_email: 'no-reply@razorpay.com',
      signature_email: null,
      default_pricing_plan_id: '1In3Yh5Mluj605',
      created_at: 1509981284,
      updated_at: 1532435637,
      deleted_at: null,
      checkout_logo_url: null,
      email_logo_url: null,
      background_image_url: null,
    },
    org_features: [],
    ...override,
  }),
};
