import { CtaViews as CTA_LABELS } from 'ui/labels/cta';

export const OTP_PARAMS = {
  loading: {
    addFunds: false,
    loading: true,
    showInput: false,
    // skipTextLabel,
    // allowSkip,
    textView: 'otp_sending_generic',
    disableCTA: true,
    errorMessage: '',
    ctaLabel: `cta.${CTA_LABELS.VERIFY}`,
  },
  sent: {
    addFunds: false,
    loading: false,
    showInput: true,
    // skipTextLabel,
    // allowSkip,
    textView: 'generic_send_otp',
    disableCTA: true,
    ctaLabel: `cta.${CTA_LABELS.VERIFY}`,
  },
  verifying: {
    addFunds: false,
    loading: true,
    showInput: false,
    // skipTextLabel,
    // allowSkip,
    textView: 'generic_send_otp',
    disableCTA: true,
    ctaLabel: `cta.${CTA_LABELS.VERIFY}`,
  },
};

export const WHITELISTED_DOMAINS = [
  'razorpay.com',
  'gmail.com',
  'outlook.com',
  'yahoo.com',
  'reddiffmail.com',
  'razorpay.com',
  'mail.com',
  'email.com',
  'usa.com',
  'myself.com',
  'consultant.com',
  'post.com',
  'dr.com',
  'execs.com',
  'europe.com',
  'engineer.com',
  'asia.com',
  'writeme.com',
  'iname.com',
  'techie.com',
  'contractor.com',
  'accountant.com',
  'workmail.com',
  'muscician.org',
  'artlover.com',
  'cheerful.com',
  'tutanota.com',
  'mailfence.com',
  'protonmail.com',
  'proton.me',
];
