export const labels = {
  ALLOTTEE_HEADER: "Allottee's Copy",
  BANK_HEADER: "Bank's Copy",
  BANK_NAME: 'E-Challan - HDFC Bank',
  HEADER: "Allottee's Copy - HDFC Bank",
  TABLE_DETAILS_LABELS: {
    beneficiaryName: 'Beneficiary Name',
    cmsCode: 'CMS Code',
    amount: 'Amount',
    eChallanNo: 'E-Challan No.',
    formNo: 'Form No.',
    uniquePropertyId: 'Unique Property ID',
    rollNo: 'Roll No',
    admissionNo: 'Admission No',
    tenderId: 'Tender ID',
    customerId: 'Customer Id',
    customerName: 'Customer Name',
    customerEmailId: 'Customer Email ID',
    customerMobileNo: 'Customer Mobile No',
    expiryOfChallan: 'Expiry of Challan',
    gst: 'GST',
    pan: 'PAN',
  },
  NOTE_DENOMINATION: [
    ['Note Denomination', 'Rs', 'Ps'],
    ['2000*', '', ''],
    ['500*', '', ''],
    ['200*', '', ''],
    ['100*', '', ''],
    ['50*', '', ''],
    ['20*', '', ''],
    ['10*', '', ''],
    ['Coins', '', ''],
    ['Total Rs. ', '', ''],
  ],
  OFFICE_USE: {
    header: '(FOR BANK USE ONLY)',
    list: [
      'Mode of Payment (Cash/Cheque/DD):',
      'Cheque No./ DD No:',
      'Details of Issuing Bank & Branch:',
    ],
  },
  HDFC_DISCLAIMERS: [
    {
      text: 'Route the depositions through CollectNow only whose path is Branch -- Collection -- New Collection -- Insurance -- Agent collection and input Deposit slip number',
      padding: 13,
    },
    {
      text: 'Accepted depositions /slips of CASH and CHEQUE to be entered on same day irrespective of clearing stamp',
      padding: 9,
    },
    {
      text: 'Please Ensure to have transaction no. on your Acknowledgement from HDFC Branch',
      padding: 9,
    },
    {
      text: 'Do not drop the payment in drop box. Pay at HDFC Bank counters only',
      padding: 6,
    },
    {
      text: 'This challan is for one time use only. Please generate a separate challan for another payment',
      padding: 9,
    },
    {
      text: 'Applicants are requested to deposit the exact amount mentioned on the challan in the form of cheque/dd/cash',
      padding: 9,
    },
  ],
  DISCLAIMER_LABEL: 'Disclaimer',
  DIPOSITOR_SIGN_LABEL: 'Signature of Depositor',
  AUTH_SIGN_LABEL: 'Authorised Signatory',
  BRANCH_LABEL: 'Branch Stamp',
} as const;
