export const extendParams = {
  instruments: [
    {
      frequency: 3,
      id: 'KjscHbhxbaguXc',
      success: false,
      timestamp: 1669613365354,
      '_[flow]': 'directpay',
      method: 'upi',
      token_id: 'token_KEB4PhxxYwqgZK',
      vpa: 'prabhjeetkalsi00@oksbi',
    },
    {
      frequency: 4,
      id: 'KjscVXl4YwsIy4',
      success: false,
      timestamp: 1669796003682,
      bank: 'SBIN',
      method: 'netbanking',
    },
    {
      frequency: 1,
      id: 'KjsdBFx9iwTOSz',
      success: false,
      timestamp: 1669293828387,
      method: 'upi',
      '_[flow]': 'intent',
      upi_app: 'com.phonepe.app',
      vendor_vpa: '@ybl',
    },
  ],
  customer: {
    contact: '+918708857906',
    haveSavedCard: true,
    tokens: {
      entity: 'collection',
      count: 1,
      items: [
        {
          id: 'token_KEB4PhxxYwqgZK',
          entity: 'token',
          token: 'HDgNLcP3NmtD52',
          bank: null,
          wallet: null,
          method: 'upi',
          vpa: {
            username: 'prabhjeetkalsi00',
            handle: 'oksbi',
            name: 'PRABHJEET  KALSI',
            status: 'valid',
            received_at: 1661840937,
          },
          recurring: false,
          recurring_details: {
            status: 'not_applicable',
            failure_reason: null,
          },
          auth_type: null,
          mrn: null,
          used_at: 1662460702,
          created_at: 1662371880,
          start_time: null,
          notes: [],
          dcc_enabled: false,
          billing_address: null,
        },
      ],
    },
    logged: true,
  },
};

export const instrumentsForAvailableMethods = [
  {
    frequency: 2,
    id: 'KjmhMqjQ3akgU7',
    success: false,
    timestamp: 1669273040119,
    method: 'card',
    token_id: 'token_KGw40fGGndjddR',
    type: 'prepaid',
    issuer: 'STCB',
    network: 'Visa',
  },
  {
    frequency: 1,
    id: 'KjsdBFx9iwTOSz',
    success: false,
    timestamp: 1669293828387,
    method: 'upi',
    '_[flow]': 'intent',
    upi_app: 'com.phonepe.app',
    vendor_vpa: '@ybl',
    score: 0.09146117454163016,
  },
  {
    frequency: 2,
    id: 'KkEpELSfXEHirh',
    success: false,
    timestamp: 1669373934226,
    provider: 'trustly',
    method: 'app',
  },
  {
    frequency: 3,
    id: 'KjscHbhxbaguXc',
    success: false,
    timestamp: 1669613365354,
    '_[flow]': 'directpay',
    method: 'upi',
    token_id: 'token_KEB4PhxxYwqgZK',
    vpa: 'prabhjeetkalsi00@oksbi',
    score: 0.20586980354645384,
  },
  {
    frequency: 1,
    id: 'KlMxJR8OFiLhwn',
    success: false,
    timestamp: 1669618960430,
    method: 'card',
    token_id: 'token_KV9N48IIj8HxdU',
    type: 'debit',
    issuer: 'SBIN',
    network: 'Visa',
  },
  {
    frequency: 4,
    id: 'KjscVXl4YwsIy4',
    success: false,
    timestamp: 1669796003682,
    bank: 'SBIN',
    method: 'netbanking',
    score: 0.2692948954393988,
  },
  {
    '_[upiqr]': true,
  },
];

export const customer = {
  contact: '+918708857906',
  haveSavedCard: true,
  tokens: {
    entity: 'collection',
    count: 2,
    items: [
      {
        id: 'token_KpObKSMsmgBxEZ',
        entity: 'token',
        token: '9yFY5et5rijcsp',
        bank: null,
        wallet: null,
        method: 'card',
        card: {
          entity: 'card',
          name: '',
          last4: '4253',
          network: 'Visa',
          type: 'debit',
          issuer: 'SBIN',
          international: false,
          emi: false,
          sub_type: 'consumer',
          token_iin: '449154271',
          expiry_month: '01',
          expiry_year: '2099',
          flows: {
            recurring: false,
            iframe: false,
          },
          cobranding_partner: null,
          country: 'IN',
          networkCode: 'visa',
          downtimeSeverity: false,
        },
        vpa: null,
        recurring: false,
        recurring_details: {
          status: 'not_applicable',
          failure_reason: null,
        },
        auth_type: null,
        mrn: null,
        used_at: 1670498117,
        created_at: 1670498115,
        expired_at: 1725128999,
        consent_taken: true,
        status: 'active',
        notes: [],
        dcc_enabled: false,
        billing_address: null,
        compliant_with_tokenisation_guidelines: true,
        plans: false,
        cvvDigits: 3,
        debitPin: false,
      },
      {
        id: 'token_KEB4PhxxYwqgZK',
        entity: 'token',
        token: 'HDgNLcP3NmtD52',
        bank: null,
        wallet: null,
        method: 'upi',
        vpa: {
          username: 'prabhjeetkalsi00',
          handle: 'oksbi',
          name: 'PRABHJEET  KALSI',
          status: 'valid',
          received_at: 1661840937,
        },
        recurring: false,
        recurring_details: {
          status: 'not_applicable',
          failure_reason: null,
        },
        auth_type: null,
        mrn: null,
        used_at: 1662460702,
        created_at: 1662371880,
        start_time: null,
        notes: [],
        dcc_enabled: false,
        billing_address: null,
      },
    ],
  },
  logged: true,
};
