export const customerTokens = {
  entity: 'collection',
  count: 3,
  items: [
    {
      id: 'token_HMpQW2ILsIXGxA',
      entity: 'token',
      token: 'DlK0TQeEFlUtcH',
      method: 'card',
      consent_taken: false,
      card: {
        country: 'US',
        entity: 'card',
        name: 'Nanda',
        last4: '7369',
        network: 'Visa',
        type: 'debit',
        issuer: 'KVBL',
        international: true,
      },
      created_at: 1623649462,
      expired_at: 1704047399,
      dcc_enabled: false,
      cvvDigits: 3,
      debitPin: false,
    },
    {
      id: 'token_GpaXi2JbdnNQo4',
      entity: 'token',
      token: '8NHRLBA1JXAzVN',
      bank: null,
      wallet: null,
      method: 'card',
      card: {
        entity: 'card',
        name: 'Siddharth Goswami',
        last4: '0176',
        network: 'MasterCard',
        type: 'debit',
        issuer: 'HDFC',
      },
      recurring: false,
      used_at: 1616391823,
      created_at: 1616391823,
      start_time: null,
      dcc_enabled: false,
    },
    {
      id: 'token_EGADb8swOCgtto',
      entity: 'token',
      token: 'GdRdKb81MWAp3e',
      method: 'card',
      consent_taken: true,
      dcc_enabled: false,
      card: {
        country: 'IN',
        entity: 'card',
        name: 'Siddharth Goswami',
        last4: '0176',
        network: 'MasterCard',
        type: 'debit',
        issuer: 'HDFC',
      },
    },
    {
      id: 'token_EGADb8swOCgtto',
      entity: 'token',
      token: 'GdRdKb81MWAp3e',
      method: 'card',
      consent_taken: true,
      dcc_enabled: false,
    },
  ],
};
