export const list = {
  // mpesa: ['Vodafone mPesa', 50],
  airtelmoney: ['Airtel Money', 32],
  amazonpay: ['Amazon Pay', 28],
  citrus: ['Citrus Wallet', 32],
  freecharge: ['Freecharge', 18],
  jiomoney: ['JioMoney', 68],
  mobikwik: ['Mobikwik', 20],
  olamoney: ['Ola Money (Postpaid + Wallet)', 22],
  paypal: ['PayPal', 20],
  paytm: ['Paytm', 18],
  payumoney: ['PayUMoney', 18],
  payzapp: ['PayZapp', 24],
  phonepe: ['PhonePe', 20],
  sbibuddy: ['SBI Buddy', 22],
  zeta: ['Zeta', 25],
  citibankrewards: ['Citibank Reward Points', 20],
  itzcash: ['Itz Cash', 20],
  paycash: ['PayCash', 20],
} as const;
