name: beta-cdn

on: deployment

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the main branch
#   push:
#     branches:
#       - master

env:
  APP_NAME: razorpay/checkout

jobs:
  beta-deploy:
    name: Deploy to Beta CDN
    runs-on: [self-hosted]
    if: github.event.deployment.environment == 'beta'
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure AWS credentials For saving the artifacts to stage bucket
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.STAGE_AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Deploy to BetaCDN Environment
        env:
          STAGE_CDN_BUCKET: rzp-1018-nonprod-betacdn
          DIR_PATH_IN_REPO: beta-cdn
          PARENT_DIR_IN_CDN: checkout
        run: |
          if [ "$(ls -A $DIR_PATH_IN_REPO)" ]; then
            echo ${{ github.ref }} ${{ github.event.deployment.environment }} checkout
            echo "pushing repo/$DIR_PATH_IN_REPO content to $STAGE_CDN_BUCKET/$PARENT_DIR_IN_CDN location"
            aws s3 cp $DIR_PATH_IN_REPO s3://$STAGE_CDN_BUCKET/$PARENT_DIR_IN_CDN/ --recursive
            aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGE_AWS_BETACDN_ID }} --paths "/$PARENT_DIR_IN_CDN/*"
            echo "Cache Invalidated, STAGE_CDN_BUCKET: $STAGE_CDN_BUCKET, DIR_PATH_IN_REPO: $DIR_PATH_IN_REPO, PARENT_DIR_IN_CDN: $PARENT_DIR_IN_CDN"
          fi

      - name: Mark Deployment Success on GitHub
        if: ${{ success() }}
        run: |
          curl --location --request POST 'https://api.github.com/repos/razorpay/checkout/deployments/${{ github.event.deployment.id }}/statuses' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "environment": "beta",
            "state": "success"
          }'
