name: cdn

on: deployment

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the main branch
#   push:
#     branches:
#       - master

env:
  APP_NAME: razorpay/checkout

jobs:
  prod-deploy:
    name: CDN Deploy
    runs-on: [self-hosted]
    if: github.event.deployment.environment == 'prod'
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure AWS credentials For saving the artifacts to stage bucket
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_SECRET }}
          aws-region: us-east-1

      - name: Deploy to Prod Environment
        env:
          PROD_CDN_BUCKET: checkout-live
          DIR_PATH_IN_REPO: cdn
        run: |
          if [ "$(ls -A $DIR_PATH_IN_REPO)" ]; then
              echo ${{ github.ref }} ${{ github.event.deployment.environment }} checkout
              echo "pushing repo/$DIR_PATH_IN_REPO content to $PROD_CDN_BUCKET location and invalidating cache"
              aws s3 cp $DIR_PATH_IN_REPO s3://$PROD_CDN_BUCKET/ --recursive  
          fi

      - name: Mark Deployment Success on GitHub
        if: ${{ success() }}
        run: |
          curl --location --request POST 'https://api.github.com/repos/razorpay/checkout/deployments/${{ github.event.deployment.id }}/statuses' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "environment": "prod",
            "state": "success"
          }'
