name: Comment Test Urls & Preview Builds
on: pull_request
jobs:
  comment:
    name: Add comment
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: ./.github/actions/comment-on-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ## Builds

            ### Commit-Based Builds are available at

            Uses **commit-sha** in url
            > https://betacdn.np.razorpay.in/checkout/builds/commit-builds/$GITHUB_COMMIT_SHA/v1/

            ### Branch Based Builds are available at

            Once a build for any commit in your branch succeeds, it will be deployed at the following Links

            > **Prod**.      : https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/v1/
            > **Canary**: https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/canary/v1/
            > **Baseline**: https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/baseline/v1/

            #### Files (Branch-Prod Based)
            - [razorpay.js](https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/v1/razorpay.js)
            - [checkout.js](https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/v1/checkout.js)
            - [checkout-frame.js](https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/v1/checkout-frame.js)
            - [checkout.css](https://betacdn.np.razorpay.in/checkout/builds/branch-builds/{branch_name}/v1/css/checkout.css)

            ## Usage

            ### Standard Checkout
            [Public Docs](https://razorpay.com/docs/payment-gateway/web-integration/standard/)


            #### API-Test Layout

            `layout.php` links for different API environments (opening in incognito mode is recommended):
            | API | Prod Test URL | Canary Test URL | Baseline Test URL |
            |--|--|--|--|
            |Production | [link](https://api.razorpay.com/test/layout.php?branch={branch_name})| [link](https://api.razorpay.com/test/layout.php?branch={branch_name}/canary)| [link](https://api.razorpay.com/test/layout.php?branch={branch_name}/baseline)|
            |Dark | [link](https://api-dark.razorpay.com/test/layout.php?branch={branch_name})| [link](https://api-dark.razorpay.com/test/layout.php?branch={branch_name}/canary)| [link](https://api-dark.razorpay.com/test/layout.php?branch={branch_name}/baseline)|
            |Beta | [link](https://beta-api.stage.razorpay.in/test/layout.php?branch={branch_name})| [link](https://beta-api.stage.razorpay.in/test/layout.php?branch={branch_name}/canary)| [link](https://beta-api.stage.razorpay.in/test/layout.php?branch={branch_name}/baseline)|
            |Func | [link](https://api-web.func.razorpay.in/test/layout.php?branch={branch_name})| [link](https://api-web.func.razorpay.in/test/layout.php?branch={branch_name}/canary)| [link](https://api-web.func.razorpay.in/test/layout.php?branch={branch_name}/baseline)|

            #### Frame Alone ( +SDK )

            **SDK Local Development**
            If you would like to connect your local development server with SDK,

            - Just connect your emulator/debug device to same WiFi and identify your `device IP:checkout-app-port`, ex: `192.168.0.107:8000`
            - Run checkout application server as `dev-start` or `live-start` or etc...

            - **Android** :
              - Set `PUBLIC_CHECKOUT_URL` in `CheckoutConstants.java` to `<server-address>/public.html` (ex: `192.168.0.107:8000/public.html`)
              - Modify `if (host != null && host.endsWith("razorpay.com")) {` **to** `if (host != null ) {` in `CheckoutPresenterImpl.java`
              - Add `android:usesCleartextTraffic="true"` to <application> in Manifest. This is to avoid HTTP blockage.
              - Run your android app in device/emulator.

            **Remote Development using android studio**
            `checkout.html` links for different API environments:

            > To use this branch on a mobile SDK, point the SDK page to one of these URLs
            -  change PUBLIC_CHECKOUT_URL to one of the below URL

            | API | Prod Test URL | Canary Test URL | Baseline Test URL |
            |--|--|--|--|
            |Production| [link](https://api.razorpay.com/test/checkout.html?branch={branch_name})|[link](https://api.razorpay.com/test/checkout.html?branch={branch_name}/canary)|[link](https://api.razorpay.com/test/checkout.html?branch={branch_name}/baseline)
            | Dark | [link](https://api-dark.razorpay.com/test/checkout.html?branch={branch_name})|[link](https://api-dark.razorpay.com/test/checkout.html?branch={branch_name}/canary) | [link](https://api-dark.razorpay.com/test/checkout.html?branch={branch_name}/baseline)
            |Beta |[link](https://beta-api.stage.razorpay.in/test/checkout.html?branch={branch_name})|[link](https://beta-api.stage.razorpay.in/test/checkout.html?branch={branch_name}/canary)|[link](https://beta-api.stage.razorpay.in/test/checkout.html?branch={branch_name}/baseline)
            |Func| [link](https://api-web.func.razorpay.in/test/checkout.html?branch={branch_name})|[link](https://api-web.func.razorpay.in/test/checkout.html?branch={branch_name}/canary)|[link](https://api-web.func.razorpay.in/test/checkout.html?branch={branch_name}/baseline)

            **Android Remote Development using debug build**
            `checkout.html` links for different API environments:

            - To use this build on a debug apk without android studio
            - Install debug apks from [here](https://docs.google.com/spreadsheets/d/1RTuj4FaYsThwijSNHxR5sCD5pVO0PzaaAh61VwtDT3I/edit#gid=0)
            - pass one of the below url as `ep` in the custom config of debug apk along with other configs

            | API | Prod Test URL | Canary Test URL | Baseline Test URL |
            |--|--|--|--|
            |Production| [link](https://api.razorpay.com/test/checkout.html?branch={branch_name})|[link](https://api.razorpay.com/test/checkout.html?branch={branch_name}/canary)|[link](https://api.razorpay.com/test/checkout.html?branch={branch_name}/baseline)
            | Dark | [link](https://api-dark.razorpay.com/test/checkout.html?branch={branch_name})|[link](https://api-dark.razorpay.com/test/checkout.html?branch={branch_name}/canary) | [link](https://api-dark.razorpay.com/test/checkout.html?branch={branch_name}/baseline)
            |Beta |[link](https://beta-api.stage.razorpay.in/test/checkout.html?branch={branch_name})|[link](https://beta-api.stage.razorpay.in/test/checkout.html?branch={branch_name}/canary)|[link](https://beta-api.stage.razorpay.in/test/checkout.html?branch={branch_name}/baseline)
            |Func| [link](https://api-web.func.razorpay.in/test/checkout.html?branch={branch_name})|[link](https://api-web.func.razorpay.in/test/checkout.html?branch={branch_name}/canary)|[link](https://api-web.func.razorpay.in/test/checkout.html?branch={branch_name}/baseline)

            ### Custom Checkout

            Note: Please add necessary checkout options **as query params** at the end of url
            [Public Docs](https://razorpay.com/docs/payment-gateway/web-integration/custom/)


            | API | Prod Test URL | Canary Test URL | Baseline Test URL |
            |--|--|--|--|
            |Production |  [link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=prod&branch={branch_name}) | [link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=prod&branch={branch_name}/canary) |[link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=prod&branch={branch_name}/baseline)|
            |Automation|[link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=qa&branch={branch_name})| [link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=qa&branch={branch_name}/canary) |[link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=qa&branch={branch_name}/baseline)
            |Dark | [link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=dark&branch={branch_name})| [link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=dark&branch={branch_name}/canary) |[link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=dark&branch={branch_name}/baseline)
            |Func | [link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=func&branch={branch_name}) |[link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=func&branch={branch_name}/canary) |[link](https://betacdn.np.razorpay.in/checkout/qa/custom-checkout.html?env=func&branch={branch_name}/baseline)
