name: Deploy

on: deployment

jobs:
  deploy:
    if: github.event.deployment.task == 'static'
    runs-on: self-hosted

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::141592612890:role/gha-prod-frontend_checkout
          aws-region: ap-south-1
          role-duration-seconds: 900

      - name: Add ENV and push
        uses: docker://amazon/aws-cli:2.7.7
        with:
          entrypoint: scripts/deploy.sh
          args: ${{ github.event.deployment.payload.commit_id }} ${{ github.event.deployment.payload.canary }} ${{ github.event.deployment.payload.baseline }} ${{ github.event.deployment.payload.production }}

      - name: Mark Deployment Success on GitHub
        if: ${{ success() }}
        run: |
          curl --location --request POST 'https://api.github.com/repos/razorpay/checkout/deployments/${{ github.event.deployment.id }}/statuses' \
          --header 'Authorization: token ${{ github.token }}' \
          --header 'Accept: application/vnd.github.everest-preview+json' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "environment": "cdn",
            "state": "success"
          }'
