# This is a basic workflow to help you get started with Actions

name: 'Canary Baseline: Build & push to Harbor'

# Controls when the action will run. Triggers the workflow on every push
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-images:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    env:
      AWS_S3_BUCKET_FOR_BUILD: rzp-1018-nonprod-betacdn
      AWS_REGION_FOR_BUILD: ap-south-1
      AWS_ACCESS_KEY: ${{ secrets.STAGE_AWS_ACCESS_KEY }}
      AWS_ACCESS_SECRET: ${{ secrets.STAGE_AWS_SECRET_KEY }}
      BUCKET_BASE_BATH_FOR_BRANCH: checkout/builds/branch-builds
      RUN_BUILD_NUMBER: ${{ github.run_id }}
      GIT_COMMIT_HASH: ${{ github.sha }}
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: docker
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Harbor
        id: harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Build and push for canary
        id: canary_build
        env:
          TRAFFIC_ENV: canary
          # build number prefix for canary: 1
          CURRENT_BUILD_NUMBER: '1${{ env.RUN_BUILD_NUMBER }}'
          BUILD_PATH_FOR_BRANCH: '${{ env.BUCKET_BASE_BATH_FOR_BRANCH }}/${{ steps.vars.outputs.branch }}'
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          build-args: |
            "AWS_S3_BUCKET_FOR_BUILD=${{ env.AWS_S3_BUCKET_FOR_BUILD }}"
            "AWS_REGION_FOR_BUILD=${{ env.AWS_REGION_FOR_BUILD }}"
            "AWS_ACCESS_KEY=${{ env.AWS_ACCESS_KEY }}"
            "AWS_ACCESS_SECRET=${{ env.AWS_ACCESS_SECRET }}"
            "BUILD_NUMBER=${{ env.CURRENT_BUILD_NUMBER }}"
            "BUILD_PATH_FOR_BRANCH=${{ env.BUILD_PATH_FOR_BRANCH }}"
            "GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}"
            "TRAFFIC_ENV=${{ env.TRAFFIC_ENV }}"
          push: true
          tags: c.rzp.io/razorpay/checkout-${{ env.TRAFFIC_ENV }}:${{ github.sha }}
      - name: Build and push for baseline
        id: baseline_build
        env:
          TRAFFIC_ENV: baseline
          # build number prefix for baseline: 2
          CURRENT_BUILD_NUMBER: '2${{ env.RUN_BUILD_NUMBER }}'
          BUILD_PATH_FOR_BRANCH: '${{ env.BUCKET_BASE_BATH_FOR_BRANCH }}/${{ steps.vars.outputs.branch }}'
        # skip build if canary is failed
        if: steps.canary_build.outcome == 'success'
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          build-args: |
            "AWS_S3_BUCKET_FOR_BUILD=${{ env.AWS_S3_BUCKET_FOR_BUILD }}"
            "AWS_REGION_FOR_BUILD=${{ env.AWS_REGION_FOR_BUILD }}"
            "AWS_ACCESS_KEY=${{ env.AWS_ACCESS_KEY }}"
            "AWS_ACCESS_SECRET=${{ env.AWS_ACCESS_SECRET }}"
            "BUILD_NUMBER=${{ env.CURRENT_BUILD_NUMBER }}"
            "BUILD_PATH_FOR_BRANCH=${{ env.BUILD_PATH_FOR_BRANCH }}"
            "GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}"
            "TRAFFIC_ENV=${{ env.TRAFFIC_ENV }}"
          push: true
          tags: c.rzp.io/razorpay/checkout--${{ env.TRAFFIC_ENV }}:${{ github.sha }}
      - name: Mark workflow status as failed
        id: failed
        if: steps.vars.outcome != 'success' || steps.docker.outcome != 'success' || steps.harbor.outcome != 'success' || steps.canary_build.outcome != 'success'|| steps.baseline_build.outcome != 'success'
        run: |
          echo 'Failing the workflow for github status check.'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 1
      - name: Mark workflow status as success
        if: steps.failed.conclusion == 'skipped'
        run: |
          echo 'Status check has passed! Build numbers for canary: 1${{ github.run_id }} and for baseline: 2${{ github.run_id }} , commit-id: ${{ github.sha }}'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 0
