# This is a basic workflow to help you get started with Actions

name: 'Build & push to registry'

# Controls when the action will run. Triggers the workflow on every push
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          secrets: AWS_CDN_BUCKET=betacdn,AWS_REGION=ap-south-1,S3_KEY_ID=${{ secrets.AWS_ACCESS_KEY }},S3_KEY_SECRET=${{ secrets.AWS_ACCESS_SECRET }},BRANCH=${{ steps.vars.outputs.branch }},BUILD_NUMBER=${{ github.run_id }},GIT_COMMIT_HASH=${{ github.sha }}
          push: true
          tags: c.rzp.io/razorpay/checkout:${{ github.sha }}
