name: Build POS Image

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          context: scripts/pos
          file: scripts/pos/Dockerfile
          push: true
          tags: c.rzp.io/razorpay/checkout:pos-${{ github.sha }}
