# This is a basic workflow to help you get started with Actions

name: 'Build & push to registry'

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        id: docker_build
        with:
          image: razorpay/checkout
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildArgs: AWS_CDN_BUCKET=betacdn, AWS_REGION=ap-south-1, S3_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}, S3_KEY_SECRET=${{ secrets.AWS_ACCESS_SECRET }}, BRANCH=${{ steps.vars.outputs.branch }}, BUILD_NUMBER=${{ github.run_id }}, GIT_COMMIT_HASH=${SHORT_SHA}
