# This is a basic workflow to help you get started with Actions

name: 'Prod: Build & push to Harbor'

# Controls when the action will run. Triggers the workflow on every push
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    # The type of runner that the job will run on
    runs-on: [self-hosted]
    env:
      AWS_S3_BUCKET_FOR_BUILD: rzp-1018-nonprod-betacdn
      AWS_REGION_FOR_BUILD: ap-south-1
      AWS_ACCESS_KEY: ${{ secrets.STAGE_AWS_ACCESS_KEY }}
      AWS_ACCESS_SECRET: ${{ secrets.STAGE_AWS_SECRET_KEY }}
      BUCKET_BASE_PATH_FOR_BRANCH: checkout/builds/branch-builds
      BUCKET_BASE_PATH_FOR_COMMIT: checkout/builds/commit-builds
      RUN_BUILD_NUMBER: ${{ github.run_id }}
      GIT_COMMIT_HASH: ${{ github.sha }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: docker
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Harbor
        id: harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Build and push to Harbor
        id: build
        env:
          # build number prefix for master: null
          CURRENT_BUILD_NUMBER: '${{ env.RUN_BUILD_NUMBER }}'
          BUILD_PATH_FOR_BRANCH: '${{ env.BUCKET_BASE_PATH_FOR_BRANCH }}/${{ steps.vars.outputs.branch }}'
          BUILD_PATH_FOR_COMMIT: '${{ env.BUCKET_BASE_PATH_FOR_COMMIT }}/${{ env.GIT_COMMIT_HASH }}'
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          build-args: |
            "AWS_S3_BUCKET_FOR_BUILD=${{ env.AWS_S3_BUCKET_FOR_BUILD }}"
            "AWS_REGION_FOR_BUILD=${{ env.AWS_REGION_FOR_BUILD }}"
            "AWS_ACCESS_KEY=${{ env.AWS_ACCESS_KEY }}"
            "AWS_ACCESS_SECRET=${{ env.AWS_ACCESS_SECRET }}"
            "BUILD_NUMBER=${{ env.CURRENT_BUILD_NUMBER }}"
            "BUILD_PATH_FOR_BRANCH=${{ env.BUILD_PATH_FOR_BRANCH }}"
            "BUILD_PATH_FOR_COMMIT=${{ env.BUILD_PATH_FOR_COMMIT }}"
            "GIT_COMMIT_HASH=${{ env.GIT_COMMIT_HASH }}"
          push: true
          tags: c.rzp.io/razorpay/checkout:${{ github.sha }}
      - name: Mark workflow status as failed
        id: failed
        if: steps.vars.outcome != 'success' || steps.docker.outcome != 'success' || steps.harbor.outcome != 'success' || steps.build.outcome != 'success'
        run: |
          echo 'Failing the workflow for github status check.'
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "failure" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 1
      - name: Mark workflow status as success
        if: steps.failed.conclusion == 'skipped'
        run: |
          echo 'Status check has passed! Build number ${{ github.run_id }} , commit-id: ${{ github.sha }} '
          curl -X POST -H "Content-Type: application/json" -H "Authorization: token ${{ github.token }}" \
          -d '{ "state" : "success" , "context" : "github/combined-status-check" , "description" : "github/combined-status-check", "target_url" : "https://github.com/${{ github.repository }}" }' \
          https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}
          exit 0
