name: Validate
on: pull_request
jobs:
  validate:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: 'app/modules'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          fail_on_error: false